var dom = document.getElementById("id");
dom.style.backgroundColor = "yellow";
dom.style.margin = "20px";
dom.style.padding = "10px";
dom.style.fontSize = "18px";
dom.style.fontWeight = "bold";
dom.style.height = "200px";
dom.style.width = "300px";
dom.style.color = "white";
